CREATE TABLE IF NOT EXISTS ingredient (
  id_ingredient int(11) NOT NULL,
  nom_ingredient text NOT NULL,
  saison text NOT NULL
);

CREATE TABLE IF NOT EXISTS recette (
  id_recette int(11) NOT NULL,
  nom_recette text NOT NULL,
  nombre_personne int(11) NOT NULL,
  temps_total time NOT NULL,
  temps_prepa time NOT NULL,
  temps_cuisson time NOT NULL,
  etapes longtext NOT NULL,
  saison text NOT NULL,
  tags text NOT NULL
);

CREATE TABLE IF NOT EXISTS recette_ingredient (
  id_ingredient_recette int(11) NOT NULL,
  id_unite int(11) NOT NULL,
  id_ingredient int(11) NOT NULL,
  id_recette int(11) NOT NULL,
  quantite int(11) NOT NULL
);

CREATE TABLE IF NOT EXISTS unite (
  id_unite int(11) NOT NULL,
  nom_unite text NOT NULL
);

INSERT INTO ingredient (id_ingredient, nom_ingredient, saison) VALUES
(1, "lait", "automne"),
(2, "oeuf", "all"),
(3, "sucre vanillé", "all"),
(4, "sucre de canne", "all"),
(5, "levure chimique", "all"),
(6, "raisins secs", "all"),
(7, "sucre glace", "all"),
(8, "chou frisé", "automne"),
(9, "tomate", "automne"),
(10, "tomates concassées", "all"),
(11, "tofus ferme", "all"),
(12, "concentré de tomates", "all"),
(13, "gousse d'ail", "all"),
(14, "oignion", "all"),
(15, "lait", "all"),
(16, "crème fraiche épaisse", "all"),
(17, "maïzena", "all"),
(18, "huile d'olive", "all"),
(19, "fromage râpé", "all"),
(20, "cumin", "all"),
(21, "curry", "all"),
(22, "paprika", "all"),
(23, "poivre ", "all"),
(24, "gingembre", "all"),
(25, "sel", "all"),
(26, "champignon de Paris", "automne"),
(27, "sucre en poudre", "all"),
(28, "alcool de fraise", "all"),
(29, "gélatine", "all"),
(30, "fraise", "ete"),
(31, "citron", "all"),
(32, "crème liquide", "all"),
(33, "sucre vanillé", "all"),
(34, "boudoir", "all"),
(35, "topinambour", "hiver"),
(36, "pommes de terre", "hiver"),
(37, "chapelure", "all"),
(38, "gruyère râpé", "all"),
(39, "navet", "printemps"),
(40, "sucre en poudre", "all"),
(41, "beurre", "all"),
(42, "poivrons", "automne"),
(43, "carotte", "automne"),
(44, "persil haché", "all"),
(50, "riz", "all"),
(51, "potiron", "automne"),
(52, "cube de bouillon", "all"),
(53, "parmesan rapé", "all"),
(54, "spaghettis", "all"),
(55, "bette à carde", "automne"),
(56, "lardons", "all"),
(57, "brocoli", "automne"),
(58, "eau", "all"),
(59, "bouquet garni", "all"),
(60, "poires", "hiver"),
(61, "chocolat noir", "all"),
(62, "farine", "all"),
(63, "cassonade", "all"),
(64, "poudre d'amande", "all"),
(65, "radis noirs", "hiver"),
(66, "chou rouge", "hiver"),
(67, "muscade rapée", "all"),
(68, "vinaigre", "all"),
(69, "pâte feuilletée", "all"),
(70, "poireaux", "hiver"),
(71, "jambon", "all"),
(72, "chèvre frais", "all"),
(73, "jaunes d'oeuf", "all"),
(74, "échalote", "all"),
(75, "sauce soja", "all"),
(76, "crevettes roses cuites non décortiquées", "all"),
(77, "lait de coco", "ete"),
(78, "curcuma", "all"),
(79, "curry jaune", "all"),
(80, "choux raves avec tiges et feuilles", "ete"),
(81, "rhubarbes", "ete"),
(82, "fenouils", "ete"),
(83, "pignon de pin", "all"),
(84, "haricots rouges", "ete"),
(85, "thym", "all"),
(86, "laurier", "all"),
(87, "gros sel", "all"),
(88, "canneloni", "all"),
(89, "épinards", "printemps"),
(90, "escalopes de porc", "all"),
(91, "comté râpé", "all"),
(92, "coulis de tomate", "all"),
(93, "escalopes de poulet", "all"),
(94, "pâtes à la semoule de riz", "all"),
(95, "germes de soja", "printemps"),
(96, "basilic", "all"),
(97, "arachides", "all"),
(98, "vinaigre blanc", "all"),
(99, "nuoc mam", "all"),
(100, "harissa", "all"),
(101, "oignons nouveaux", "printemps"),
(102, "feuille de menthe", "all"),
(103, "ciboulette", "all"),
(104, "jus de citron", "all"),
(105, "moutarde", "all"),
(106, "vinaigre balsamique", "all"),
(107, "concombre", "all"),
(108, "fromage frais", "all"),
(109, "betteraves rouges", "printemps");

--
-- Déchargement des données de la table "recette"
--

INSERT INTO recette (id_recette, nom_recette, nombre_personne, temps_total, temps_prepa, temps_cuisson, etapes, saison, tags) VALUES
(1, "Lasagnes de chou vert frisé", 4, "00:45:00", "00:25:00", "00:20:00", "Étape 1<br/><br/>Préparer une béchamel light : dans une petite casserole, faire fondre la crème fraiche. Dès les premières bulles, ajouter la maizena puis le lait, un peu de sel et de poivre (et de noix de muscade si vous avez) et laisser épaissir en touillant. Couper le feu des que la béchamel commence à prendre.<br/><br/>Étape 2<br/><br/>Préparer la sauce tomate : dans une casserole, faire chauffer l'huile et y faire revenir l'ail écrasé, l'oignon, le tofu coupé en tout petits dés, et les champignons. Ajouter les épices.<br/><br/>Étape 3<br/><br/>Une fois que c'est bien roussis et que le tofu a pris le goût des épices, ajouter les tomates coupées en petits dés et le concentré de tomates avec un demi-verre d'eau.<br/>Étape 4<br/><br/>Préchauffer le four à 250°C (thermostat 8).<br/><br/>Étape 5<br/><br/>Dresser les lasagnes : dans un plat à gratin, disposer une couche de feuille de choux, puis une couche de tomate (la moitié de la préparation), puis une couche de béchamel (un tiers). Recommencer encore une fois et terminer par une couche de choux et le dernier tiers de béchamel.<br/><br/>Étape 6<br/><br/>Parsemer d'un peu de gruyère râpé.<br/>Étape 7<br/><br/>Enfourner pendant 20-25 minutes. C'est prêt quand l'eau rendue par le chou est évaporée et que le dessus est bien doré. Le chou doit rester croquant.", "automne", "Facile |Bon marché | Plat principal | Végétarien"),
(2, "Charlotte aux fraises", 6, "01:00:00", "01:00:00", "00:00:00", "Étape 1<br/><br/>Préparer un sirop en portant à ébullition 15 cl d'eau et 80 g de sucre. Ôter du feu et laisser refroidir, ensuite y mettre l'alcool de fraise.<br/><br/>Étape 2<br/><br/>Faire tremper la gélatine dans un bol d'eau froide.<br/><br/>Étape 3<br/><br/>Laver et équeuter les fraises et en mettre 8 entières de côté.<br/>Mettre les autres fraises dans un mixeur avec le jus de citron et mixer jusqu'à obtenir une purée lisse. Transvaser cette purée dans une passoire afin de récolter le coulis et retenir les grains.<br/><br/>Étape 4<br/><br/>Prélever un quart de ce coulis et le faire chauffer doucement dans une casserole en y incorporant la gélatine essorée et le restant de sucre.<br/><br/>Étape 5<br/><br/>Ensuite, mélanger le coulis obtenu (chaud) avec le coulis froid. Laisser tiédir à température ambiante.<br/><br/>Étape 6<br/><br/>Mettre la crème liquide dans un saladier et mettre au congélateur 20 min. Puis la fouetter de façon à obtenir une crème chantilly. Mettre le sucre vanillé, remuer doucement et mettre en attente au frais.<br/><br/>Étape 7<br/><br/>Placer le récipient où se trouve le coulis dans un récipient + grand rempli de glaçons. Remuer le coulis jusqu'à constater son épaississement. A ce moment, l'ôter des glaçons et y ajouter la chantilly en tournant délicatement. Laisser à température ambiante.<br/><br/>Étape 8<br/><br/>Couper les 8 fraises mises de côté dans leur hauteur.<br/>Tapisser le fond et les parois du moule avec des boudoirs trempés (vite fait) dans le sirop (les tailler si besoin). Pour les parois : côté bombé contre le moule.<br/><br/>Étape 9<br/><br/>Verser un tiers de la crème puis parsemer de fraises coupées (la moitié).<br/><br/>Étape 10<br/><br/>Couvrir du second tiers de crème, disposer le restant de fraises coupées. Terminer par le dernier tiers de crème. Finir par une couche de biscuits (toujours trempés dans le sirop).<br/><br/>Étape 11<br/><br/>Mettre du film plastique sur le plat et laisser au frais 6h (une nuit est l'idéal) avant de démouler.", "ete", "Dessert |Bon marché | Difficile"),
(3, "Gratin de topinambours", 2, "00:40:00", "00:10:00", "00:30:00", "Étape 1<br/><br/>Peler les topinambours et les pommes de terre.<br/><br/>Étape 2<br/><br/>Les couper en grosses rondelles.<br/><br/>Étape 3<br/><br/>Les faire cuire à la vapeur.<br/><br/>Étape 4<br/><br/>Préchauffer le four à 200°C (thermostat 6-7).<br/><br/>Étape 5<br/><br/>Écraser à la fourchette ou au presse-purée.<br/><br/>Étape 6<br/><br/>Verser 10 cl de crème liquide, bien mélanger. Le mélange doit avoir la consistance d'une purée épaisse, Ajouter de la crème si nécessaire.<br/><br/>Étape 7<br/><br/>Verser dans un plat à gratin.<br/><br/>Étape 8<br/><br/>Saupoudrer de chapelure puis de fromage râpé.<br/><br/>Étape 9<br/><br/>Faire gratiner 10 minutes environ au four.", "hiver", "Accompagnement | Végétarien | Four | Facile |Bon marché"),
(4, "Navets caramélisés", 4, "00:25:00", "00:10:00", "00:15:00", "Étape 1<br/><br/>Epluchez et lavez les navets.<br/><br/>Étape 2<br/><br/>Dans une casserole, portez de l'eau à ébullition et mettez-y les navets à cuire 10/15 min selon leur grosseur (vérifier la cuisson avec la pointe d'un couteau, comme pour les pommes de terre).<br/><br/>Étape 3<br/><br/>Egouttez-les lorsqu'ils sont cuits.<br/><br/>Étape 4<br/><br/>Dans une poêle, faire chauffer un peu de beurre, y faire revenir les navets pour qu'ils dorent et saupoudrer de sucre. Remuer. Ajouter un petit peu d'eau (10 cl) pour finaliser. Faire revenir les navets jusqu'à ce que tout soit évaporé dans la poêle.<br/><br/>Étape 5<br/><br/>Servez avec un confit de canard par exemple, un régal", "printemps", "Accompagnement | Végétarien | Très facile | Bon marché "),
(5, "Ratatouille aux carottes", 4, "01:05:00", "00:20:00", "00:45:00", "Étape 1<br/><br/>Éplucher et émincer les carottes en rondelles.<br/><br/>Étape 2<br/><br/>Les faire revenir dans une cocotte avec de l'huile d'olive chaude.<br/><br/>Étape 3<br/><br/>Couper les tomates en quartiers, épépiner et émincer les poivrons en lanières, émincer les oignons.<br/><br/>Étape 4<br/><br/>Retirer les carottes une fois dorées de la cocotte, y mettre les poivrons.<br/><br/>Étape 5<br/><br/>Faire de même et remplacer par les oignons, puis les tomates.<br/><br/>Étape 6<br/><br/>Enfin, remettre tous les légumes dans la cocotte, saler et poivrer.<br/><br/>Étape 7<br/><br/>Ajouter l'ail haché et le persil, laisser mijoter 10 min et servir.", "automne", "Plat principal | Végétarien | Très Facile | Bon marché"),
(6, "Risotto au potiron", 4, "01:00:00", "00:40:00", "00:20:00", "Étape 1<br/><br/>Pelez le potiron, éliminez les graines et coupez-le en tranches fines.<br/><br/>Étape 2<br/><br/>Hachez menu l'oignon et faites-le revenir dans 20 g de beurre, ajoutez le poiton, salez et laissez cuire à feu lent, en mélangeant et en versant un peu de bouillon.<br/><br/>Étape 3<br/><br/>Quand le potiron est défait, versez le riz et faites-le cuire pendant 18 minutes en rajoutant du bouillon chaud au fur et à mesure qu'il est absorbé.<br/><br/>Étape 4<br/><br/>Ajoutez le lait, mélangez à feu vif, ajouter le poivre, le persil et une bonne dose de parmesan. Mélangez rapidement avant de servir de façon que tous les ingrédients soient parfaitement amalgamés.", "automne", "Très facile | Bon marché | Halloween | Plat Principal"),
(7, "Spaghetti aux bettes", 4, "00:40:00", "00:15:00", "00:25:00", "Étape 1<br/><br/>Préparer les bettes, les couper en morceaux, garder les plus belles parties des feuilles puis les faires cuire dans de l'eau salée pendant 10 minutes.<br/><br/>Étape 2<br/><br/>Faire cuire les spaghettis pendant 10 minutes environs.<br/><br/>Étape 3<br/><br/>Pendant la cuisson des bettes et des spaghettis, couper les 2 oignons en petits morceaux, les blondir à la poêle en même temps que les lardons.<br/><br/>Étape 4<br/><br/>Une fois que tout est prêt, dans une grosse casserole, mettre à feu doux les spaghettis, les bettes, les lardons avec les oignons, bien mélanger puis ajouter la crème liquide, sel et poivre.<br/><br/>Étape 5<br/><br/>Laisser 5 minutes en ajoutant un peu d'eau si ça accroche.", "automne", "Pâtes | Plat Principal | Facile | Coût moyen"),
(8, "Velouté de brocolis", 6, "00:45:00", "00:15:00", "00:30:00", "Étape 1<br/><br/>Nettoyez les bouquets de brocolis, raccourcissez les trognons de 5 cm et retirez les feuilles.<br/><br/>Étape 2<br/><br/>Faites fondre les oignons à feu doux dans une noix de beurre. Ajoutez les brocolis.<br/><br/>Étape 3 <br/><br/>Faites dissoudre les cubes de bouillon dans 1,5 L d'eau<br/><br/>Étape 4<br/><br/>Mouillez du bouillon et portez à ébullition. Ajoutez le bouquet garni et laissez mijoter 30 min, jusqu'à ce que les brocolis soient cuits à points.<br/><br/>Étape 5<br/>Mixez le tout et ajouter la crème, assaisonnez à votre goût.", "automne", "Entrée | Soupe |Très Facile | Bon Marché"),
(9, "Crumble poires - chocolat", 4, "01:00:00", "00:30:00", "00:30:00", "Étape 1<br/><br/>Mélanger, la farine, 100g de beurre, la cassonade et la poudre d'amandes jusqu'à obtention d'une pâte sableuse. Mettre au frais pendant 30 mn.<br/><br/>Étape 2<br/><br/>Beurrer un plat à four et y déposer les carrés de chocolat.<br/><br/>Étape 3<br/><br/>Ébouillanter les poires 20 secondes, les peler et les couper en quartiers.<br/><br/>Étape 4<br/><br/>Les placer sur les carrés de chocolat.<br/><br/>Étape 5<br/><br/>Sortir la pâte du réfrigérateur et la répartir sur les poires et le chocolat.<br/><br/>Étape 6<br/><br/>Mettre au four à th°C 6-7 pendant 30 mn.<br/><br/>Étape 7<br/><br/>Servir tiède.", "hiver", "Dessert | Au Four | Végétarien | Très Facile | Bon Marché"),
(10, "Soufflé de radis noir", 4, "01:35:00", "00:35:00", "01:00:00", "Étape 1<br/><br/>Versez 1,5 l d'eau dans une casserole avec le cube de bouillon ou fond de volaille.<br/><br/>Étape 2<br/><br/>Laissez chauffer pendant 10 minutes.<br/><br/>Étape 3<br/><br/>Préparation des légumes :<br/><br/>Étape 4<br/><br/>Épluchez les radis noirs et coupez-les en gros dès.<br/><br/>Étape 5<br/><br/>Épluchez les pommes de terre et coupez-les en gros dès.<br/><br/>Étape 6<br/><br/>Après les 10 min d'infusion, ajoutez le radis et les pommes de terre dans le bouillon.<br/><br/>Étape 7<br/><br/>Laissez cuire à feu couvert 40 minutes.<br/><br/>Étape 8<br/><br/>Le radis doit être très tendre.<br/><br/>Étape 9<br/><br/>Égouttez bien. Mixez-le ensuite pour obtenir une purée.(astuce : réserver un peu de bouillon pour facilité la fabrication de la purée et éviter une purée trop compacte).<br/><br/>Étape 10<br/><br/>Pour la béchamel :<br/><br/>Étape 11<br/><br/>Dans une casserole, faites fondre le beurre.<br/><br/>Étape 12<br/><br/>Dès qu'il est fondu, ajoutez la farine.<br/><br/>Étape 13<br/><br/>Remuez avec un fouet et laissez cuire à feu doux sans laisser colorer pendant 5 à 10 minutes. Ajoutez ensuite le lait. Salez et poivrez.<br/><br/>Étape 14<br/><br/>Laissez cuire à feu doux 15 minutes en remuant tout le temps.<br/><br/>Étape 15<br/><br/>La béchamel est prête quand elle forme une boule assez compacte et collante dans la casserole.<br/><br/>Étape 16<br/><br/>Hors du feu, mélangez la béchamel avec les jaunes d’œufs, le parmesan râpé et la purée de radis. Préchauffez le four th 6/7 (200°C).<br/><br/>Étape 17<br/><br/>Montez les blancs en neige avec la maïzena. Incorporez-les délicatement au mélange précédent.<br/><br/>Étape 18<br/><br/>Versez la préparation dans le moule.<br/><br/>Étape 19<br/><br/>Enfournez pour 20 minutes.<br/><br/>Étape 20<br/><br/>C'est prêt ! Il n'y a plus qu'à déguster !", "hiver", "Végétarien | Au Four | Plat Principal"),
(11, "Soupe au chou rouge", 6, "00:45:00", "00:15:00", "00:30:00", "Étape 1<br/><br/>Nettoyer le chou, lui ôter le trognon et les grosses côtes, puis le détailler en <br/>fines lanières.<br/><br/>Étape 2<br/><br/>Dans une marmite, faire rissoler les lardons dans le saindoux. Ajouter ensuite le chou en remuant, puis couvrir et laisser étuver 8 min à feu très doux.<br/><br/>Étape 3<br/><br/>Délayer le cube de bouillon dans les 2 litres d'eau chaude, le verser dans la marmite. Assaisonner de sel, poivre et muscade râpée à votre goût.<br/><br/>Étape 4<br/><br/>Ajouter enfin le vinaigre et le sucre, puis laisser cuire à couvert encore quelques minutes en surveillant.<br/><br/>Étape 5<br/><br/>Mettre en soupière, puis ajouter la crème fraîche pour lier.<br/><br/>Étape 6<br/><br/>Servir et déguster bien chaud.", "hiver", "Soupe | Entrée | Facile | Bon Marché"),
(12, "Tourte Poireaux, Jambon et Chèvre", 4, "00:40:00", "00:10:00", "00:30:00", "Étape 1<br/><br/>Etalez la pâte dans une tourtière (laisser la feuille de papier de sulfurisé entre le plat et la pâte pour ne pas que cela attache).<br/><br/>Étape 2<br/><br/>Piquer la pâte et enfourner à 200°C pendant 10 mn.<br/><br/>Étape 3<br/><br/>Pendant ce temps faire revenir les poireaux dans du beurre, saler et poivrer.<br/><br/>Étape 4<br/><br/>Étaler les poireaux sur la pâte, ajouter au dessus le jambon coupé en petits morceaux et le chèvre détaillé en fines tranches.<br/><br/>Étape 5<br/><br/>Mélanger la crème et les 2 jaunes d’œufs, saler et poivrer. Verser le mélange sur la tourte.<br/><br/>Étape 6<br/><br/>Enfourner 30 min et c'est prêt.", "hiver", "Au Four | Plat Principal | Facile | Bon Marché"),
(13, "Curry de chou rave et crevettes", 4, "00:45:00", "00:20:00", "00:25:00", "Étape 1<br/><br/>Eplucher et émincer l’oignon, l’échalote et l’ail. Dans un bol mélanger l’oignon, l’échalote, l’ail, le curry, le curcuma, 2 cuillères à soupe d’huile de d’olive, un peu de poivre.<br/><br/>Étape 2<br/><br/>Si vous avez un pilon, c’est encore mieux, mettez le tout au pilon et écraser jusqu’à l’obtention d’une pâte de curry.<br/><br/>Étape 3<br/><br/>Éplucher les choux raves (enlever toutes les parties vertes et filandreuses). Garder les feuilles. Couper les choux en dés de 1 cm. Les faire cuire à la vapeur pendant 9 minutes.<br/><br/>Étape 4<br/><br/>Pendant ce temps, épluchez les crevettes.<br/><br/>Étape 5<br/><br/>Séparer les feuilles des choux des tiges. Émincer les feuilles au couteau.<br/><br/>Étape 6<br/><br/>Dans un wok bien chaud, mettre 1 cuillère à soupe d’huile d’olive. Verser le mélange oignon-échalote-ail et laisser cuire 2-3 minutes en remuant.<br/><br/>Étape 7<br/><br/>Ajouter les feuilles de choux émincées, les crevettes et 1 cuillère à soupe de sauce soja. Cuire en remuant 5 minutes.<br/><br/>Étape 8<br/><br/>Ajouter les dés de chou cuits. Cuire en remuant 2 minutes.<br/><br/>Étape 9<br/><br/>Ajouter le lait de coco ou la crème. Porter à ébullition. Vérifier l’assaisonnement et ajuster au besoin.<br/><br/>Étape 10<br/><br/>Servir avec du riz ou des nouilles asiatiques.", "ete", "Plat principal |Asie | Facile | Bon Marché "),
(14, "Gâteau à la rhubarbe", 6, "01:10:00", "00:30:00", "00:40:00", "Étape 1<br/><br/>Allumer le four.<br/><br/>Étape 2<br/><br/>Dans une grande tourtière, mettre 180g de sucre et 100g de beurre. Passer au four une dizaine de minutes pour que le mélange fonde. Mettre dessus la rhubarbe coupée en petits morceaux.<br/><br/>Étape 3<br/><br/>Pour le gâteau, travailler le reste du beurre en crème, ajouter le reste du sucre et bien battre le mélange. Incorporer ensuite les oeufs entiers, la farine, le lait, la vanille et la levure.<br/><br/>Étape 4<br/><br/>Verser la pâte sur les morceaux de rhubarbe.<br/><br/>Étape 5<br/><br/>Cuire à four modéré Th 6 (180°C) pendant 40 mn.<br/><br/>Étape 6<br/><br/>Lorsque le gâteau est cuit, attendre 10 mn avant de le démouler.<br/><br/>Étape 7<br/><br/>Le retourner sur un plat et le laisser se décoller tout seul, ce qui demande quelques minutes.<br/><br/>Étape 8<br/><br/>Bon appétit !!!", "ete", "Dessert | Végétarien | Au Four | Très Facile | Bon Marché"),
(15, "Velouté de fenouil", 2, "00:30:00", "00:15:00", "00:15:00", "Étape 1<br/><br/>découper les fenouils en morceaux puis les laver. Egouter.<br/><br/>Étape 2<br/><br/>Couper les oignons en lamelles. Faire revenir fenouil et oignon dans une cocotte minute avec une cuillère à soupe d'huile d'olive.<br/><br/>Étape 3<br/><br/>Ajouter la gousse d'ail et couvrir d'eau. Ajouter le bouillon cube et fermer la cocotte. Compter un quart d'heure après la rotation de la soupape.<br/><br/>Étape 4<br/><br/>Ajouter ensuite la cuillère à soupe de pignons de pin et la noix de muscade râpée puis mixer le tout avec un pied à soupe.<br/><br/>Étape 5<br/><br/>Ajouter la crème fraîche selon convenance.<br/><br/>Étape 6<br/><br/>Bon appétit!", "ete", "Entrée | Végétarien | Très facile | Bon Marché"),
(16, "Haricots rouges à la créole", 4, "02:15:00", "00:15:00", "02:00:00", "Étape 1<br/><br/>Attention, si on utilise des haricots secs, un temps de trempage de 10 heures environ, est nécessaire (pendant la nuit?) ainsi qu'une cuisson couverte de 2 heures à feu doux. L'objectif recherché étant que les grains soit fondant sous le palais. Vous pouvez aussi y parvenir gâce à une cocotte ou un autocuiseur. Pensez à conservez une partie du jus de cuisson (très riche en vitamines) et nécessaire pour la recette. Vous pouvez ensuite conserver les grains dans votre congélateur ou les cuisiner aussitôt.<br/><br/>Étape 2<br/><br/>Ecrasez les gousses d'ail, le gingembre, le piment et le gros sel dans un pilon ou un petit mixer pour obtenir une pâte homogène.<br/>Étape 3<br/>Coupez finement les oignons.<br/><br/>Étape 4<br/><br/>Dans une casserole (une petite marmite en fonte étant l'idéal), chauffez 2 cuillerées d'huile avant d'y incorporer les oignons jusqu'à ce qu'ils obtiennent une teinte rousse.<br/><br/>Étape 5<br/><br/>Faîtes revenir alors le mélange d'épices écrasées dans la casserole. Ensuite le curcuma, afin de les parer d'un beau jaune vif.<br/><br/>Étape 6<br/><br/>Ajoutez immédiatement les haricots rouges avec leur jus, le thym et le quatre épices : bien remuer le tout.<br/><br/>Étape 7<br/><br/>Laissez cuire une quinzaine de minutes en veillant à remuer de temps en temps et en écrasant délicatement environ 1/3 des haricots jusqu'à ce que le jus prennent l'aspect d'un velouté crémeux.<br/><br/>Étape 8<br/><br/>Salez, poivrez.<br/><br/>Étape 9<br/><br/>Servez chaud, comme accompagnement d'un cari de poulet, d'un rougail saucisses ou autres.", "ete", "Végétarien | Accompagnement | Créole |Facile | Bon Marché"),
(17, "Cannelloni aux épinards", 2, "01:30:00", "00:45:00", "00:45:00", "Étape 1<br/><br/>Hacher séparément les épinards et la viande.<br/><br/>Étape 2<br/><br/>Emincer les oignons, et les faire fondre dans le beurre.<br/><br/>Étape 3<br/><br/>Ajouter les épinards et faire évaporer l'eau. Ajouter la viande, l'ail, le sel, le poivre et la muscade. Faire cuire 10 min. Laisser refroidir. Ajouter l'oeuf et la moitié du fromage.<br/><br/>Étape 4<br/><br/>Fourrer les cannelloni. Les disposer dans un plat à four. Napper de coulis et parsemer avec le reste de fromage.<br/><br/>Étape 5<br/><br/>Cuire 30 min à 200)C (thermostat 6-7), puis gratiner quelques minutes sous le grill.", "printemps", "Plat principal | Au four | Facile | Bon Marché"),
(18, "Feuilletés aux champignons", 7, "01:00:00", "00:20:00", "00:40:00", "Étape 1<br/><br/>Hachez les échalotes.<br/><br/>Étape 2<br/><br/>Dans une sauteuse, mettez 25 g de beurre et les échalotes sur feu doux pendant 5 minutes.<br/><br/>Étape 3<br/><br/>Ajoutez les champignons et le reste du beurre, salez et poivrez.<br/><br/>Étape 4<br/><br/>Augmentez le feu et laissez cuire 10 minutes,remuez de temps en temps.<br/><br/>Étape 5<br/><br/>Ensuite, versez la crème dans la sauteuse. Laissez frémir 5 minutes, la sauce doit épaissir et réduire.<br/><br/>Étape 6<br/><br/>Hors du feu, ajoutez le persil, la moitié du gruyère et 1 jaune d'oeuf. Mélangez et laissez refroidir.<br/><br/>Étape 7<br/><br/>Préchauffez le four à 210°C (thermostat 8).<br/><br/>Étape 8<br/><br/>Étalez la pâte.<br/><br/>Étape 9<br/><br/>Coupez des carrés afin d'en obtenir 7.<br/><br/>Étape 10<br/><br/>Répartissez la préparation aux champignons au centre.<br/><br/>Étape 11<br/><br/>Fermez vos carrés comme un petit paquet en pinçant les pointes ensemble. Bien <br/>souder les bords toujours en pinçant.<br/><br/>Étape 12<br/><br/>Badigeonnez avec un pinceau de jaune d'oeuf mélangé au lait.<br/><br/>Étape 13<br/><br/>Mettez sur une plaque de cuisson sur une feuille de papier sulfurisée<br/><br/>Étape 14<br/><br/>Enfournez pendant 20 minutes à 180°C (thermostat 6).<br/><br/>Étape 15<br/><br/>A la sortie du four parsemez de gruyère râpé.", "printemps", "Végétarien | Accompagnement | Très Facile | Bon Marché"),
(19, "Pad thaï", 6, "00:21:00", "00:05:00", "00:16:00", "Étape 1<br/><br/>Faire chauffer un wok ou une grosse poêle.<br/>Ajouter 1 cuillère d'huile, ajouter le basilic, le laisser frire pendant une minute.<br/><br/>Étape 2<br/><br/>Retirer le basilic et ajouter un autre cuillère d'huile à la poêle, faire revenir le poulet, ajouter le sel et le paprika, faire cuire pendant 4 à 5 minutes.<br/><br/>Étape 3<br/><br/>Ajouter les œufs et bien mélanger (ça doit ressembler à des œufs brouillés).<br/><br/>Étape 4<br/><br/>Vider le wok et réserver dans un plat.<br/><br/>Étape 5<br/><br/>Ajouter la dernière cuillère d'huile dans la poêle. Mettre l'ail, le vinaigre le nuoc nam et le sucre, faire cuire pendant 2 minutes.<br/><br/>Étape 6<br/><br/>Ajouter les pâtes cuites dans la sauce. Mettre le piment et les arachides, ajouter le poulet et les légumes au tout et bien mélanger.<br/><br/>Étape 7<br/><br/>Dresser dans un plat et décorer avec le basilic frit.<br/><br/>Étape 8<br/><br/>Pour accompagner ce plat, un Crémant de Loire blanc millésimé, avec ses notes toastées et sa fraîcheur, se mariera parfaitement avec les notes thaï de ce plat.", "printemps", "Plat Principal | Asie | Facile | Bon Marché | Rapide"),
(20, "Verrine de betterave rouge et concombre", 8, "00:15:00", "00:15:00", "00:00:00", "Étape 1<br/><br/>Mixez la betterave rouge avec les 2/3 tiers de fromage frais, la moutarde, le vinaigre, la crème fraîche, le jus de citron.<br/><br/>Étape 2<br/><br/>Assaisonnez avec sel, poivre, ciboulette.<br/><br/>Étape 3<br/><br/>Réservez au frais.<br/><br/>Étape 4<br/><br/>Coupez en dés le concombre. Mélangez avec le reste de fromage frais.<br/><br/>Étape 5<br/><br/>Dans une verrine, mettez de la crème de betteraves et décorez avec les dés de concombre.<br/><br/>Étape 6<br/><br/>Servez frais.", "printemps", "Entrée | Rapide | Végétarien | Facile | Bon Marché");

--
-- Déchargement des données de la table "recette_ingredient"
--

INSERT INTO recette_ingredient (id_ingredient_recette, id_unite, id_ingredient, id_recette, quantite) VALUES
(1, 11, 8, 1, 1),
(2, 11, 9, 1, 3),
(3, 2, 11, 1, 150),
(4, 11, 26, 1, 4),
(5, 3, 12, 1, 1),
(6, 11, 13, 1, 2),
(7, 11, 14, 1, 1),
(8, 8, 15, 1, 25),
(9, 3, 16, 1, 2),
(10, 3, 17, 1, 3),
(11, 10, 19, 1, 1),
(12, 12, 22, 1, 1),
(13, 12, 23, 1, 1),
(14, 12, 20, 1, 1),
(15, 12, 21, 1, 1),
(16, 12, 24, 1, 1),
(27, 2, 27, 2, 140),
(28, 3, 28, 2, 1),
(29, 13, 29, 2, 6),
(30, 2, 30, 2, 500),
(31, 11, 31, 2, 1),
(32, 8, 32, 2, 40),
(33, 14, 3, 2, 1),
(34, 11, 34, 2, 26),
(35, 2, 35, 3, 400),
(36, 2, 36, 3, 400),
(37, 8, 32, 3, 10),
(38, 2, 37, 3, 200),
(39, 2, 38, 3, 200),
(40, 2, 39, 4, 500),
(41, 3, 40, 4, 1),
(42, 2, 41, 4, 10),
(43, 2, 9, 5, 300),
(44, 2, 43, 5, 150),
(45, 2, 42, 5, 300),
(46, 2, 14, 5, 300),
(47, 11, 13, 5, 2),
(48, 12, 44, 5, 1),
(49, 8, 18, 5, 5),
(50, 12, 23, 5, 1),
(51, 12, 25, 5, 1),
(52, 2, 41, 6, 40),
(53, 8, 15, 6, 25),
(54, 3, 44, 6, 1),
(55, 2, 14, 6, 150),
(56, 2, 50, 6, 350),
(57, 2, 51, 6, 500),
(58, 1, 52, 6, 1),
(59, 12, 53, 6, 1),
(60, 8, 32, 7, 40),
(61, 11, 14, 7, 2),
(62, 12, 23, 7, 1),
(63, 12, 25, 7, 1),
(64, 2, 54, 7, 250),
(65, 5, 55, 7, 1),
(66, 2, 56, 7, 200),
(67, 11, 14, 8, 2),
(68, 11, 52, 8, 3),
(69, 9, 32, 8, 3),
(70, 12, 23, 8, 1),
(71, 12, 25, 8, 1),
(72, 5, 57, 8, 1),
(73, 7, 58, 8, 2),
(74, 1, 59, 8, 1),
(75, 2, 41, 9, 110),
(76, 11, 60, 9, 4),
(77, 2, 61, 9, 130),
(78, 2, 63, 9, 50),
(79, 2, 64, 9, 15),
(80, 11, 36, 10, 3),
(81, 2, 53, 10, 100),
(82, 11, 2, 10, 2),
(83, 8, 15, 10, 25),
(84, 2, 41, 10, 50),
(85, 2, 62, 10, 50),
(86, 1, 52, 10, 1),
(87, 4, 17, 10, 1),
(88, 12, 23, 10, 1),
(89, 12, 25, 10, 1),
(90, 2, 65, 10, 800),
(91, 2, 56, 11, 200),
(92, 2, 41, 11, 40),
(93, 1, 52, 11, 1),
(94, 7, 58, 11, 2),
(95, 3, 63, 11, 1),
(96, 3, 16, 11, 2),
(97, 12, 25, 11, 1),
(98, 12, 23, 11, 1),
(99, 2, 66, 11, 400),
(100, 12, 67, 11, 1),
(101, 3, 68, 11, 2),
(102, 8, 32, 12, 25),
(103, 15, 69, 12, 1),
(104, 11, 70, 12, 3),
(105, 16, 71, 12, 1),
(106, 11, 72, 12, 2),
(107, 11, 73, 12, 2),
(108, 11, 13, 13, 2),
(109, 3, 18, 13, 3),
(110, 11, 14, 13, 1),
(111, 12, 23, 13, 1),
(112, 11, 80, 13, 2),
(113, 4, 21, 13, 1),
(114, 4, 78, 13, 1),
(115, 8, 77, 13, 15),
(116, 2, 76, 13, 500),
(117, 3, 75, 13, 1),
(118, 11, 74, 13, 1),
(119, 2, 41, 14, 175),
(120, 2, 40, 14, 380),
(121, 11, 2, 14, 3),
(122, 8, 15, 14, 10),
(123, 14, 5, 14, 1),
(124, 14, 3, 14, 1),
(125, 2, 81, 14, 500),
(126, 11, 14, 15, 1),
(127, 11, 13, 15, 1),
(128, 2, 67, 15, 5),
(129, 1, 52, 15, 1),
(130, 3, 18, 15, 1),
(131, 12, 16, 15, 1),
(132, 11, 82, 15, 2),
(133, 3, 83, 15, 1),
(134, 11, 14, 16, 2),
(135, 11, 13, 16, 3),
(136, 2, 24, 16, 100),
(137, 4, 78, 16, 1),
(138, 12, 25, 16, 1),
(139, 12, 23, 16, 1),
(140, 2, 84, 16, 250),
(141, 17, 85, 16, 3),
(142, 18, 86, 16, 2),
(143, 12, 87, 16, 1),
(160, 11, 14, 17, 1),
(161, 11, 13, 17, 1),
(162, 12, 23, 17, 1),
(163, 12, 25, 17, 1),
(164, 12, 67, 17, 1),
(165, 2, 41, 17, 10),
(166, 11, 2, 17, 1),
(167, 11, 88, 17, 10),
(168, 2, 89, 17, 150),
(169, 2, 90, 17, 150),
(170, 2, 91, 17, 150),
(171, 8, 92, 17, 200),
(172, 2, 69, 18, 300),
(173, 2, 26, 18, 700),
(174, 11, 74, 18, 2),
(175, 12, 44, 18, 1),
(176, 2, 62, 18, 30),
(177, 11, 73, 18, 2),
(178, 3, 15, 18, 1),
(179, 2, 41, 18, 50),
(180, 2, 38, 18, 100),
(181, 3, 16, 18, 2),
(182, 12, 23, 18, 1),
(183, 12, 25, 18, 1),
(184, 8, 18, 19, 5),
(185, 3, 22, 19, 2),
(186, 11, 2, 19, 2),
(187, 11, 13, 19, 3),
(188, 3, 63, 19, 2),
(189, 11, 93, 19, 3),
(190, 2, 94, 19, 200),
(191, 19, 96, 19, 1),
(192, 3, 97, 19, 3),
(193, 3, 99, 19, 2),
(194, 4, 100, 19, 1),
(195, 11, 101, 19, 2),
(196, 12, 102, 19, 1),
(197, 3, 16, 20, 2),
(198, 2, 108, 20, 250),
(199, 11, 107, 20, 1),
(200, 3, 106, 20, 1),
(201, 4, 105, 20, 1),
(202, 8, 104, 20, 10),
(203, 12, 103, 20, 1);

--
-- Déchargement des données de la table "unite"
--

INSERT INTO unite (id_unite, nom_unite) VALUES
(1, "portion"),
(2, "g"),
(3, "cuillère à soupe"),
(4, "cuillère à café"),
(5, "kg"),
(6, "mg"),
(7, "L"),
(8, "cl"),
(9, "dl"),
(10, "poignée"),
(11, "none"),
(12, "à votre convenance"),
(13, "feuille"),
(14, "sachet"),
(15, "rouleau"),
(16, "tranche"),
(17, "branches"),
(18, "feuilles"),
(19, "bouquet");
